server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: auth-server
security:
  user:
    name: admin
    password: admin
